defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: 421990735784.dkr.ecr.us-east-1.amazonaws.com/ci-build-environment:node-12
      aws_auth:
        aws_access_key_id: $AWS_ACCESS_KEY_ID
        aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    - image: circleci/redis

version: 2
jobs:
  build:
    <<: *defaults
    parallelism: 1

    steps:
      - checkout
      # see if we have the node_modules cached already
      - restore_cache:
          key: 'v1-node-module-cache-{{ .Branch }}-{{ checksum "package.json" }}'
      - run: npm i
      # save the node_modules cache
      - save_cache:
          key: 'v1-node-module-cache-{{ .Branch }}-{{ checksum "package.json" }}'
          paths:
            - ~/workspace/node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - .
  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run unit tests and generate code coverage
          command: npm run coverage
      - store_test_results:
          path: ./test-results
      - store_artifacts: # upload test coverage report as artifact
          path: ./coverage/lcov-report
          prefix: tests
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run: npm run prepublish
      - run:
          command: chmod +x ./deploy/artifactory.sh && ./deploy/artifactory.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - unit_test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - hold
