export enum OpenTelemetryAttributes {
  QueueName = 'bullmq.queue.name',
  WorkerName = 'bullmq.worker.name',
  BulkCount = 'bullmq.job.bulk.count',
  BulkNames = 'bullmq.job.bulk.names',
  JobName = 'bullmq.job.name',
  JobId = 'bullmq.job.id',
  JobKey = 'bullmq.job.key',
  JobOptions = 'bullmq.job.options',
  JobProgress = 'bullmq.job.progress',
  QueueDrainDelay = 'bullmq.queue.drain.delay',
  QueueGrace = 'bullmq.queue.grace',
  QueueCleanLimit = 'bullmq.queue.clean.limit',
  JobType = 'bullmq.job.type',
  JobTimestamp = 'bullmq.job.timestamp',
  QueueOptions = 'bullmq.queue.options',
  QueueEventMaxLength = 'bullmq.queue.event.max.length',
}
