export enum TelemetryAttributes {
  QueueName = 'bullmq.queue.name',
  WorkerName = 'bullmq.worker.name',
  BulkCount = 'bullmq.job.bulk.count',
  BulkNames = 'bullmq.job.bulk.names',
  JobName = 'bullmq.job.name',
  JobId = 'bullmq.job.id',
  JobKey = 'bullmq.job.key',
  JobOptions = 'bullmq.job.options',
  JobProgress = 'bullmq.job.progress',
  QueueDrainDelay = 'bullmq.queue.drain.delay',
  QueueGrace = 'bullmq.queue.grace',
  QueueCleanLimit = 'bullmq.queue.clean.limit',
  JobType = 'bullmq.job.type',
  JobTimestamp = 'bullmq.job.timestamp',
  QueueOptions = 'bullmq.queue.options',
  QueueEventMaxLength = 'bullmq.queue.event.max.length',
  WorkerOptions = 'bullmq.worker.options',
  WorkerToken = 'bullmq.worker.token',
  WorkerId = 'bullmq.worker.id',
  WorkerRateLimit = 'bullmq.worker.rate.limit',
  WorkerDoNotWaitActive = 'bullmq.worker.do.not.wait.active',
  WorkerForceClose = 'bullmq.worker.force.close',
  WorkerJobsInvolved = 'bullmq.worker.jobs.involved',
}
