---
config:
  layout: elk
  look: neo
---
stateDiagram
  direction TB
  state delayChoice <<choice>>
  state priorityChoice <<choice>>
  state errorChoice <<choice>>
  state jobFinished <<join>>
  state workerPickup <<join>>
  [*] --> delayChoice: job added
  delayChoice --> priorityChoice:when delay is 0
  delayChoice --> Delayed:when delay is greater than 0
  priorityChoice --> Prioritized:when priority is greater than 0
  priorityChoice --> Wait:when priority is 0
  Delayed --> priorityChoice
  errorChoice --> delayChoice:when backoff strategy enabled
  errorChoice --> Delayed:when manual call moveToDelayed
  errorChoice --> priorityChoice:when manual call moveToWait or dynamic rate limit is applied
  errorChoice --> Failed:error is Unrecoverable or all attempts made are consumed or all attempts started are consumed
  Prioritized --> workerPickup
  Wait --> workerPickup
  workerPickup --> Active:picked by a worker when not rate-limited or paused and below max concurrency
  Active --> errorChoice:when error is thrown
  Active --> Failed:contains deferred error
  Active --> Completed:no error is thrown
  Completed --> jobFinished
  Failed --> jobFinished
  jobFinished --> [*]:job finished
