/**
 * Generates src/postgres/sql-scripts.ts, inlining every '.sql' file under
 * src/postgres/commands and src/postgres/migrations as an exported string
 * constant.
 *
 * This mirrors what the Redis backend does with its '.lua' scripts: the SQL
 * becomes part of the compiled JavaScript, so the published package (and any
 * single-file bundle — bun build --compile, esbuild --bundle, pkg, Node SEA,
 * deno compile) no longer needs the '.sql' files on disk at runtime.
 *
 * @see https://github.com/taskforcesh/bullmq/issues/4603
 *
 * The '.sql' files stay in the repository as the source of truth (they are
 * shared verbatim with the Python/Elixir/PHP/Rust ports); run this script to
 * regenerate the module after changing any of them.
 */
const fs = require('fs');
const path = require('path');
const { argv } = require('process');

const readFile = fs.promises.readFile;
const writeFile = fs.promises.writeFile;
const readdir = fs.promises.readdir;

const COMMANDS_DIR = 'src/postgres/commands';
const MIGRATIONS_DIR = 'src/postgres/migrations';
const OUTPUT_FILE = 'src/postgres/sql-scripts.ts';

const HEADER = `// Auto-generated by scripts/generateSqlScripts.js — DO NOT EDIT.
//
// Inlined at build time from src/postgres/commands/*.sql and
// src/postgres/migrations/*.sql, which remain the source of truth (shared
// verbatim with the Python/Elixir/PHP/Rust ports). Regenerate with
// 'yarn generate:sql:scripts' after editing any .sql file.
//
// Inlining removes the runtime filesystem dependency (readFileSync from a
// __dirname-derived path), which broke every single-file bundler:
// https://github.com/taskforcesh/bullmq/issues/4603

/**
 * Runtime query SQL, keyed by command name (filename without the .sql
 * extension), matching the keys used by loadCommandSql().
 */
export const SQL_COMMANDS: Record<string, string> = {
`;

const MIGRATIONS_HEADER = `};

/**
 * Schema migration SQL, keyed by filename (e.g. '0001_schema.sql'), matching
 * the keys used by loadMigrationSql().
 */
export const SQL_MIGRATIONS: Record<string, string> = {
`;

async function collectSqlFiles(dir) {
  const files = await readdir(dir);
  const sqlFiles = files.filter(file => path.extname(file) === '.sql').sort();

  if (sqlFiles.length === 0) {
    throw new Error(`No .sql files found in ${dir}!`);
  }
  return sqlFiles;
}

async function inlineFile(dir, file) {
  const content = await readFile(path.join(dir, file), 'utf8');

  // JSON.stringify escapes backslashes, quotes and newlines and is always a
  // valid TypeScript string literal. Template literals (as used for the Lua
  // scripts) are not an option here because SQL sources contain backticks.
  return `  ${JSON.stringify(file)}: ${JSON.stringify(content)},\n`;
}

async function main() {
  const root = path.normalize(argv[2] || process.cwd());
  const commandsDir = path.join(root, COMMANDS_DIR);
  const migrationsDir = path.join(root, MIGRATIONS_DIR);
  const outputPath = path.join(root, OUTPUT_FILE);

  const commandFiles = await collectSqlFiles(commandsDir);
  const migrationFiles = await collectSqlFiles(migrationsDir);

  let content = HEADER;
  for (const file of commandFiles) {
    content += await inlineFile(commandsDir, file);
  }

  content += MIGRATIONS_HEADER;
  for (const file of migrationFiles) {
    content += await inlineFile(migrationsDir, file);
  }
  content += '};\n';

  const existing = fs.existsSync(outputPath)
    ? await readFile(outputPath, 'utf8')
    : undefined;
  if (existing !== content) {
    await writeFile(outputPath, content);
    console.log(
      `Generated ${OUTPUT_FILE} (${commandFiles.length} commands, ${migrationFiles.length} migrations)`,
    );
  }
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
