name: OSV-Scanner Scan (default branch + schedule)

on:
  schedule:
    - cron: '30 12 * * 1'
  push:
    branches: [master]

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  scan-scheduled:
    uses: 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.3.8'
    with:
      # fail the build only on the scheduled full scan, not on every push to master
      fail-on-vuln: ${{ github.event_name == 'schedule' }}
      scan-args: |-
        --config=osv-scanner.toml
        -r
        ./
